### ISSUE TITLE
[BUG] If grade is SG, parsing fails.

### ISSUE THREAD

**Issue by miyamamoto** [hmasdev/pyjpboatrace#64]
If grade is SG, parsing fails.
https://www.boatrace.jp/owpc/pc/race/index?hd=20221030

```
from datetime import date
import json
from pyjpboatrace import PyJPBoatrace
boatrace_tools = PyJPBoatrace()
dic = boatrace_tools.get_stadiums(d=date(2022,10,30))
with open('data.json', 'w', encoding='utf-8') as f:
    json.dump(dic, f, ensure_ascii=False)
boatrace_tools.close()
```
...
'Always': {'status': '-',
  'grade': ['[FailedToParse]is-SGa'],
  'timeframe': '',
  'title': 'The 69th Boat Race Derby',
  'period': ['2022-10-25', '2022-10-30'],
  'day': 'Last day'},
...

**Comment by hmasdev** [comment]
Thanks @miyamamoto 
The bug is caused because `grade_mapper` in `scraper/_parser/parse_html_index.py` does not have a key corresponding to "SG".

https://github.com/hmasdev/pyjpboatrace/blob/main/pyjpboatrace/scraper/_parser/parse_html_index.py#L4-L12

I have fixed the bug in the following PR: #65
